# -*- coding: utf-8 -*-
"""Calculate sum and average

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKrcbumeyb2L_Id4405hN9px7DSDbmms
"""

count = 0
sum = 0.0
number = 1

while number != 0:
        number = int(input(""))
        # This line adds the current value of number
        sum = sum + number
        # Keeps track of how many numbers a user has entered
        count += 1

if count == 0:
        print("Input some numbers")
else:
        print("Average and Sum of the above numbers are:", sum / (count-1), sum)