# -*- coding: utf-8 -*-
"""Find Number based on frequency

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100TBAM7jcI8_IEPm8hLrGVgNGJxEFddu
"""

# Number with lowest frequency
x = [1, 1, 1, 1, 2, 2,2,2,2,2,2,2,2,2, 3, 4, 5]

# Initialize variables to store the mode and its frequency
mode = None
min_count = float('inf')

# Iterate through each element in the list
for num in x:
    count = x.count(num)  # Count how many times the current element appears in the list
    if count < min_count:
        # If the count of the current element is greater than the previous maximum count,
        # update the mode and the maximum count
        mode = num
        min_count = count

print("Mode:", mode)

# Number with Highest frequency
x = [1, 1, 1, 1, 2, 2,2,2,2,2,2,2,2,2, 3, 4, 5]

# Initialize variables to store the mode and its frequency
mode = None
min_count = 0

# Iterate through each element in the list
for num in x:
    count = x.count(num)  # Count how many times the current element appears in the list
    if count > min_count:
        # If the count of the current element is greater than the previous maximum count,
        # update the mode and the maximum count
        mode = num
        min_count = count

print("Mode:", mode)