# -*- coding: utf-8 -*-
"""Get triangle type from given inputs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKrcbumeyb2L_Id4405hN9px7DSDbmms
"""

def main():
  a = int(input())
  b = int(input())
  c = int(input())
  if a == b == c:
    print("equilateral triangle")
  elif a != b and b != c and c != a:
    print("scalene triangle")
  elif a == b or b == c or c == a:
    print("isosceles triangle")
  else:
    print("Not defined")
main();