# -*- coding: utf-8 -*-
"""Get Next Date

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UPq8D4op-07QpRWFAwn3Ic2itn58Celg

#### Write a Python program to get next day of a given date.

#### Sample Output

#### Input a year: 1974
#### Input a month [1-12]: 2
#### Input a day [1-31]: 15
#### The next date is [yyyy-mm-dd] 1974-2-16.

#### Input:
#### 2018 7 14
#### New Section
#### Output:
#### The next date is [yyyy-mm-dd] 2018-7-15.
"""

#write your code inside main function
year = int(input())
month = int(input())
day = int(input())

if (year % 400 == 0):
  leap_year = True
elif (year % 100 == 0):
  leap_year = False
elif (year % 4 == 0):
  leap_year = True
else:
  leap_year = False


if month in (1, 3, 5, 7, 8, 10, 12):
  month_length = 31
elif month == 2:
  if leap_year:
    month_length = 29
  else:
    month_length = 28
else:
  month_length = 30

if day < month_length:
  day += 1
else:
  day = 1
  if month == 12:
    month = 1
    year += 1
  else:
    month += 1
print ("The next date is [yyyy-mm-dd] %d-%d-%d." % (year, month, day))